; PlatformIO Project Configuration File
; ESP8266 Alexa to IR Controller (Wemo Plug Emulation with FauxmoESP 2.2.1)

[env:nodemcuv2]
board = nodemcuv2
platform = espressif8266

framework = arduino
monitor_speed = 115200

lib_deps =
    symlink://lib/FauxmoESP_Patched
    me-no-dev/ESPAsyncTCP@^1.2.2
    crankyoldgit/IRremoteESP8266@^2.8.6
